name: "Branch off "
run-name: Create a ${{ inputs.branch-name }}
on:
  workflow_call:
    inputs:
      branch-name:
        description: 'The version you want to release.'
        default: 'release'
        required: true
        type: string


jobs:
  

  branch-from-main:
    env:
      BRANCH_NAME: ${{ inputs.branch-name }}/${{ github.event.inputs.version }}
    name: "Draft a branch from main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release branch
        run: |
          echo $${{ github.event }}
          git checkout -b $BRANCH_NAME

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Push new branch
        run: git push origin $BRANCH_NAME

      - name: create pull request
        if: ${{ inputs.branch-name == 'release' }}
        run: gh pr create -B main -H $BRANCH_NAME --title '${{ inputs.branch-name }} -> $BRANCH_NAME' --body "- PR for the incoming release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
