name: "Branch off master"

on:
  workflow_call:
    inputs:
      hotfix:
        description: 'Determine if branch is for hotfix'
        default: false
        required: true
        type: boolean
      branch-name:
        description: 'Branch name'
        default: release
        required: true
        type: string

jobs:

  branch-from-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release branch
        run: | #dapat main to lagi
          echo $${{ github.event }}  
          git checkout -b ${{ inputs.branch-name }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Push new branch
        run: git push origin ${{ inputs.branch-name }}

      - name: Create PR to release
        if: inputs.hotfix != true
        run: gh pr create -B ${{ inputs.branch-name }} -H develop --title 'develop -> ${{ inputs.branch-name }}' --body "- ${{ inputs.branch-name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}