name: Draft hotfix release
run-name: Draft hotfix/${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to hotfix release'
        required: true
      profile:
        required: true
        description: "DEV/TEST/PROD"
        type: choice
        options:
          - DEV
          - TEST
        default: DEV
env:
  PROFILE: ${{ inputs.profile }}
jobs:
  draft-new-hotfix-release:
    name: Create hotfix release
    uses: ./.github/workflows/branch-off-main.yml
    with:
      hotfix: true
      branch-name: $PROFILE
       