name: Draft hotfix release
run-name: Draft hotfix/${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to hotfix release'
        required: true

jobs:
  draft-new-hotfix-release:
    name: Create hotfix release
    uses: ./.github/workflows/branch-off-main.yml
    with:
      hotfix: false
      branch-name: hotfix/${{ inputs.version }}
       