name: Draft new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release'
        required: true

jobs:
  draft-new-release:
    name: Draft a new release
    uses: ./.github/workflows/branch-off-main.yml
    with:
      hotfix: false
      branch-name: release/${{ inputs.version }}