name: Draft hotfix release
run-name: Draft hotfix/${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to hotfix release'
        required: true
      profile:
        required: true
        description: "DEV/TEST/PROD"
        type: choice
        options:
          - DEV
          - TEST
        default: DEV
env:
  PROFILE: ${{ inputs.profile }}
jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set
        run: | 
          echo "env_profile=$PROFILE" >> $GITHUB_OUTPUT
  draft-new-hotfix-release:
    needs: set-env
    name: Create hotfix release
    uses: ./.github/workflows/branch-off-main.yml
    with:
      hotfix: true
      branch-name: ${{ needs.set-env.outputs.env_profile }}