name: "Draft hotfix"
run-name: Create hotfix/${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    uses: ./.github/workflows/branch-off-main.yml
    with:
      for-prod: true
      branch-name: hotfix/${{ inputs.version }}
       