name: Create PR of Release to Main

on:
  push:
    branches:
      - 'release/**'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: create pull request
        run: gh pr create -B main -H ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" --title '${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" -> master' --body "- PR for the incoming release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

