name: Create PR of Release to Main

on:
  push:
    branches:
      - 'release/**'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: create pull request
        run: gh pr create -B main -H ${GITHUB_REF#refs/heads/} --title "Release ${NOW}" --body "- ${GITHUB_REF#refs/heads/} -> master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
