name: Create PR of Release to Main

on:
  push:
    branches:
      - 'release/**'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: create pull request
        run: gh pr create -B release/test-8 -H main --title 'develop -> release' --body "- PR for the incoming release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
