name: Create PR of Release to Main

on:
  push:
    branches:
      - 'release/**'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        
      - name: create pull request
        run: gh pr create -B ${GITHUB_REF#refs/heads/} -H main --title '${GITHUB_REF#refs/heads/} -> master' --body "- Release ${NOW}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

