name: Create PR of Release to Main

on:
  push:
    branches:
      - 'release/**'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo ${GITHUB_REF#refs/heads/}
      - name: create pull request
        run: gh pr create -B main -H ${GITHUB_REF#refs/heads/} --title '${GITHUB_REF#refs/heads/} -> master' --body "- Release ${NOW}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

