name: Run Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Action
        id: greet
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with: 
          who-to-greet: Ali
      - name: Log Greet time
        run: echo "${{ steps.greet.outputs.time }}"