name: Test Workflow run
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
  run-01:
    needs: [run-shell-command]
    runs-on: windows-latest
    environment:
      name: TEST ENV 01
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash
  run-02:
    needs: [run-shell-command]
    runs-on: windows-latest
    environment:
      name: TEST ENV 02
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash