name: Workflow Commands
on: [push]

jobs:
  testfing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set error echo
        run: echo "::error::test"
      - name: Log and error
        run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Log a warning
        run: echo "::warning title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Log a notice
        run: echo "::notice title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing 