name: Working with DIR & Shells 
on: [push]
defaults:
  run:
    shell: cmd
jobs:
  display-info-one:
    runs-on: windows-latest
    steps:
      - name: Display work dir and list of files
        run: |
          cd
          dir
      - name: Change working directory 
        working-directory: /
        run: cd
  display-wd-info-mac:
    runs-on: macos-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Python Shell
        shell: python
        run: |
          import platform 
          print(platform.processor())

